### ISSUE TITLE
* not escaped when Unserializing

### ISSUE THREAD

**Issue by artemOP** [leafvmaple/luadata#5]
When trying to turn [this](https://tycoon-njyvop.users.cfx.re/status/config/omni_self_storage) table into a dict of its item the * used in the `cost` sections is not escaped causing the error:
```
Exception: Unserialize luadata failed on pos 96:
    = 25*10^6,
  
        ^
    unexpected character.
```
is this just something to try parse out myself or something that could be included on a lib level

**Comment by tinymins** [comment]
It seems that you a trying to parse a lua expression in data string, which is not supported in this lib.
This lib do not have a real lua environment, it just parse data by string reading and analysing, so it is not possible for this lib to run a real lua expression and get the result.

There is a solution for you, try to execute your source data in a real lua vm, and serialize it without expression first.

**Comment by artemOP** [comment]
Update:
 some relatively simple parsing fixed my issue, rather than having to go to a full vm just to parse the table
